import { NextResponse } from "next/server";
import { getBrandBrain } from "@/lib/getBrandBrain";
import { supabaseAdmin } from "@/lib/supabaseServer";
import { requireOwner } from "@/lib/requireOwner";
export const maxDuration=45;const URL="https://api.anthropic.com/v1/messages";const MODEL=process.env.ANTHROPIC_PITCH_MODEL??"claude-haiku-4-5";
function json(t:string){const c=t.trim().replace(/^```json\s*/i,"").replace(/^```\s*/i,"").replace(/```$/i,"").trim();try{return JSON.parse(c)}catch{const a=c.indexOf("{"),b=c.lastIndexOf("}");if(a>=0&&b>a)return JSON.parse(c.slice(a,b+1));throw new Error("Unreadable pitch response")}}
export async function POST(){try{await requireOwner();const key=process.env.ANTHROPIC_API_KEY;if(!key)return NextResponse.json({error:"ANTHROPIC_API_KEY is required."},{status:400});const db=supabaseAdmin(),brain=await getBrandBrain(),today=new Date().toISOString().slice(0,10);const [{data:existing},{data:rejected}]=await Promise.all([db.from("candidates").select("headline").eq("slate_date",today).eq("candidate_kind","pitch"),db.from("reels").select("headline,review_note").eq("status","rejected").order("updated_at",{ascending:false}).limit(25)]);const used=(existing??[]).map((x:any)=>x.headline);const memory=(rejected??[]).map((x:any)=>`${x.headline}${x.review_note?` (${x.review_note})`:""}`).join(" | ");const prompt=`You are Film Room's editorial desk. Generate exactly ONE fresh MEN'S college-sports reel pitch, clearly different from: ${used.join(" | ")}.
Rejected ideas/feedback to learn from and avoid repeating: ${memory||"none yet"}.
It is football season: strongly prefer MEN'S COLLEGE FOOTBALL unless a men's basketball idea is exceptionally timely. HIGHLIGHTS are the core product. No women's sports. No marching-band, generic crowd, stadium-atmosphere or tradition-only pitches. Favor superstar player highlights, school/team on-field highlights, rivalry/game highlights, iconic plays, or a verified interview/testimony hook followed by highlights. Require enough searchable footage for at least two source videos. Use real teams, year and recognizable male players. 15-35 sec.
Voice: ${(brain?.voice?.principles??[]).join(" ")}.
Score viral potential honestly from 0-10; 9.3+ means genuinely fire. Return ONLY JSON: {"headline":"...","sport":"football|basketball","summary":"...","whyToday":"...","viewerFeeling":"...","searchQueries":["...","..."],"template":"PLAYER_HIGHLIGHT|TEAM_HIGHLIGHT|RIVALRY|MOMENT|INTERVIEW_STORY|STORY","teams":["..."],"year":"...","players":["..."],"anticipatedLength":"...","openingConcept":"...","clipPlan":"...","overallScore":9.1}`;const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000);try{const r=await fetch(URL,{method:"POST",headers:{"content-type":"application/json","x-api-key":key,"anthropic-version":"2023-06-01"},body:JSON.stringify({model:MODEL,max_tokens:900,temperature:.82,messages:[{role:"user",content:prompt}]}),signal:controller.signal});const payload=await r.json();if(!r.ok)throw new Error(payload?.error?.message??`Anthropic request failed (${r.status})`);const text=(payload?.content??[]).filter((b:any)=>b?.type==="text").map((b:any)=>b.text).join("\n"),s=json(text);if(!s?.headline)throw new Error("The Brain did not return a usable pitch.");const score=Math.max(0,Math.min(10,Number(s.overallScore)||8.5));const story={headline:String(s.headline),sport:s.sport==="basketball"?"basketball":"football",summary:String(s.summary??""),whyToday:String(s.whyToday??"Strong Film Room idea."),viewerFeeling:String(s.viewerFeeling??"awe"),searchQueries:Array.isArray(s.searchQueries)?s.searchQueries.slice(0,4).map(String):[String(s.headline)],template:["PLAYER_HIGHLIGHT","TEAM_HIGHLIGHT","RIVALRY","MOMENT","INTERVIEW_STORY","STORY"].includes(s.template)?s.template:"PLAYER_HIGHLIGHT",teams:Array.isArray(s.teams)?s.teams.slice(0,4).map(String):[],year:String(s.year??"—"),players:Array.isArray(s.players)?s.players.slice(0,6).map(String):[],anticipatedLength:String(s.anticipatedLength??"20–30 sec"),openingConcept:String(s.openingConcept??"Open on the strongest highlight."),clipPlan:String(s.clipPlan??"Hook → escalating highlights → payoff."),overallScore:score};const row={slate_date:today,candidate_kind:"pitch",headline:story.headline,sport:story.sport,summary:story.summary,source_urls:[],score,score_breakdown:{story,kind:"pitch",why_today:story.whyToday,viewer_feeling:story.viewerFeeling,template:story.template,teams:story.teams,year:story.year,players:story.players,anticipated_length:story.anticipatedLength,opening_concept:story.openingConcept,clip_plan:story.clipPlan,recommendation:"ALTERNATE"},selected:false,rejection_reason:null};const{data,error}=await db.from("candidates").insert(row).select().single();if(error)throw error;return NextResponse.json({pitch:data})}finally{clearTimeout(timer)}}catch(err:any){console.error("Generate-more pitch failed:",err);const status=err?.message==="UNAUTHORIZED"?401:err?.message==="FORBIDDEN"?403:500;return NextResponse.json({error:status===401?"Please sign in again.":status===403?"Owner access required.":err?.message??"Could not generate another pitch."},{status})}}
