"use client";

import { useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";
import { useRouter } from "next/navigation";

type Pitch={id:string;headline:string;sport:string;summary:string|null;score:number|null;score_breakdown:any;selected:boolean};
type Job={id:string;headline:string;slot:number;status:"queued"|"building"|"ready"|"failed";message?:string};

const categories:any={
 PLAYER_SPOTLIGHT:{icon:"◎",label:"PLAYER SPOTLIGHT"},
 TEAM_SCHOOL_SPOTLIGHT:{icon:"◈",label:"SCHOOL SPOTLIGHT"},
 MOMENT_GAME:{icon:"▶",label:"MOMENT / GAME"},
 STORY:{icon:"◉",label:"STORY / TESTIMONY"},
 TIMELESS_HIGHLIGHT:{icon:"∞",label:"TIMELESS HIGHLIGHT"},
 PLAYER_HIGHLIGHT:{icon:"◎",label:"PLAYER SPOTLIGHT"},
 TEAM_HIGHLIGHT:{icon:"◈",label:"SCHOOL SPOTLIGHT"},
 RIVALRY:{icon:"⚡",label:"RIVALRY HIGHLIGHTS"},
 MOMENT:{icon:"▶",label:"ICONIC HIGHLIGHT"},
 INTERVIEW_STORY:{icon:"◉",label:"STORY / TESTIMONY"}
};
const phases=["SCANNING SOURCES","RANKING MOMENTS","GROUNDING CLIPS","BUILDING THE EDIT","LOCKING THE RECIPE"];
function meta(p:Pitch){return p.score_breakdown??{};}
function recommendation(p:Pitch){const m=meta(p);return m.recommendation??m.story?.recommendation??"ALTERNATE";}
function template(p:Pitch){const m=meta(p);return m.template??m.story?.template??"PLAYER_HIGHLIGHT";}
function fireCount(score:number){if(score>=9.5)return 5;if(score>=9.2)return 4;if(score>=8.8)return 3;if(score>=8.3)return 2;if(score>=7.8)return 1;return 0;}

export default function PitchBoard({pitches}:{pitches:Pitch[]}){
 const router=useRouter();
 const recommended=pitches.filter(p=>["PRIMARY","SECONDARY"].includes(recommendation(p)));
 const initial=(recommended.length===2?recommended:pitches.slice(0,2)).map(p=>p.id);
 const [selected,setSelected]=useState<string[]>(initial);
 const [loading,setLoading]=useState(false);const [moreLoading,setMoreLoading]=useState(false);const [error,setError]=useState<string|null>(null);const [jobs,setJobs]=useState<Job[]>([]);const [phase,setPhase]=useState(0);
 const selectedSet=useMemo(()=>new Set(selected),[selected]);
 useEffect(()=>{if(!loading){setPhase(0);return;}const t=window.setInterval(()=>setPhase(v=>Math.min(v+1,4)),2800);return()=>clearInterval(t)},[loading]);
 function toggle(id:string){setSelected(s=>s.includes(id)?s.filter(x=>x!==id):s.length>=3?s:[...s,id]);}
 async function generateMore(){setMoreLoading(true);setError(null);try{const r=await fetch("/api/generate-more-pitch",{method:"POST"});const d=await r.json().catch(()=>({}));if(!r.ok||d.error)throw new Error(d.error??"Could not generate another pitch");router.refresh()}catch(e:any){setError(e.message)}finally{setMoreLoading(false)}}
 async function build(){if(!selected.length)return;setLoading(true);setError(null);const chosen=selected.map(id=>pitches.find(p=>p.id===id)!).filter(Boolean);setJobs(chosen.map((p,i)=>({id:p.id,headline:p.headline,slot:i+1,status:"queued"})));let ready=0;for(let i=0;i<chosen.length;i++){const p=chosen[i];setJobs(j=>j.map(x=>x.id===p.id?{...x,status:"building",message:"Finding the best footage and edit structure…"}:x));try{const r=await fetch("/api/build-one",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:p.id,slot:i+1})});const d=await r.json().catch(()=>({}));if(!r.ok||d.error)throw new Error(d.error??`Build failed (${r.status})`);ready++;setJobs(j=>j.map(x=>x.id===p.id?{...x,status:"ready",message:"Editor-ready recipe built."}:x))}catch(e:any){setJobs(j=>j.map(x=>x.id===p.id?{...x,status:"failed",message:e.message??"Build failed"}:x))}}setLoading(false);if(ready)router.refresh();if(ready<chosen.length)setError(`${ready}/${chosen.length} reels built. Open any failed reel to adjust its source or transcript.`)}
 function card(p:Pitch,index:number){const m=meta(p),rec=recommendation(p),pick=rec!=="ALTERNATE",t=template(p),cat=categories[t]??categories.PLAYER_HIGHLIGHT,score=Number(p.score??0),fires=fireCount(score),teams=Array.isArray(m.teams)?m.teams:m.story?.teams??[],players=Array.isArray(m.players)?m.players:m.story?.players??[],year=m.year??m.story?.year??"—",len=m.anticipated_length??m.story?.anticipatedLength??"20–30 sec",reason=m.recommendation_reason??m.story?.recommendationReason??m.why_today??"Strong Film Room fit.",opening=m.opening_concept??m.story?.openingConcept,clip=m.clip_plan??m.story?.clipPlan,active=selectedSet.has(p.id);return <button key={p.id} onClick={()=>toggle(p.id)} disabled={loading} className={`text-left panel pitch-card p-6 transition-all duration-300 ${pick?"brain-pick-card":""} ${active?"ring-2 ring-jelly/35 -translate-y-1 bg-sidecar/40":"hover:-translate-y-1 hover:bg-white"}`}>
  <div className="flex justify-between gap-3 mb-4"><div className="flex flex-wrap gap-2"><span className={pick?"brain-badge":"alt-badge"}>{pick?`✦ BRAIN PICK · POST ${rec==="PRIMARY"?"01":"02"}`:`OPTION ${String(index+1).padStart(2,"0")}`}</span><span className="format-chip"><b className="mr-1">{cat.icon}</b>{cat.label}</span></div><span className={`h-7 w-7 rounded-full border grid place-items-center ${active?"bg-jelly text-white border-jelly":"bg-white text-transparent border-rule"}`}>✓</span></div>
  <div className="flex items-start justify-between gap-4"><h3 className="font-display text-2xl tracking-wide text-ink">{p.headline}</h3><div className="shrink-0 text-right"><div className="text-[15px] leading-none" title={`${fires}/5 viral fire rating`}>{fires?"🔥".repeat(fires):"·"}</div><div className="font-mono text-[9px] tracking-wider text-dim mt-1">VIRAL {score.toFixed(1)}</div></div></div>
  <p className="text-sm text-dim leading-6 mt-2 mb-4">{p.summary}</p>
  {pick&&<div className="recommendation-box"><div className="data-label text-jelly">WHY THIS IS ONE OF TODAY'S TWO</div><p>{reason}</p></div>}
  <div className="grid grid-cols-2 gap-3 my-4 text-xs"><div className="data-cell"><div className="data-label">TEAM / SCHOOL</div><b>{teams.length?teams.join(" · "):"TBD"}</b></div><div className="data-cell warm"><div className="data-label">YEAR / ERA</div><b>{year}</b></div><div className="data-cell col-span-2"><div className="data-label">PLAYERS</div><div>{players.length?players.join(" · "):"No single player required"}</div></div></div>
  {opening&&<div className="intel-strip"><span>HOOK</span><p>{opening}</p></div>}{clip&&<div className="intel-strip"><span>EDIT</span><p>{clip}</p></div>}
  <div className="border-t border-rule pt-4 mt-4 flex justify-between font-mono text-[10px] tracking-wider"><span className="text-jelly">EST. {len}</span><span className="text-dim">{cat.label}</span></div>
 </button>}
 const picks=pitches.filter(p=>["PRIMARY","SECONDARY"].includes(recommendation(p)));const alts=pitches.filter(p=>!picks.some(x=>x.id===p.id));const pairing=meta(picks[0]??pitches[0])?.pairing_logic??meta(picks[0]??pitches[0])?.story?.pairingLogic;
 const overlay=loading&&typeof document!=="undefined"?createPortal(<div className="fixed inset-0 z-[9999] bg-[#fffaf1]/95 backdrop-blur-xl flex items-center justify-center p-6"><div className="w-full max-w-4xl rounded-[3rem] border border-rule bg-white/90 shadow-[0_50px_140px_rgba(37,121,155,.22)] overflow-hidden" style={{perspective:"1200px"}}><div className="grid md:grid-cols-2"><div className="p-10 bg-sinbad/15"><div className="label-eyebrow mb-2">FILM ROOM / ASSEMBLY ENGINE</div><h2 className="font-display text-4xl tracking-wide">BUILDING THE REELS</h2><div className="relative h-72 mt-8 rounded-[2.5rem] bg-white/70 border border-rule overflow-hidden"><div className="absolute inset-0 grid place-items-center"><div className="h-28 w-28 rounded-full bg-jelly text-white grid place-items-center font-display text-xl shadow-[0_25px_50px_rgba(37,121,155,.28)] animate-[pulse_2s_ease-in-out_infinite]">REEL</div></div>{["HOOK","SOURCE","MOMENTS","EDIT"].map((x,i)=><div key={x} className="absolute rounded-full border border-jelly/20 bg-sinbad/35 px-5 py-3 font-mono text-[9px] tracking-widest text-dim animate-[float_3s_ease-in-out_infinite]" style={{left:["8%","58%","16%","60%"][i],top:["18%","20%","68%","68%"][i],animationDelay:`${i*.35}s`}}>{x}</div>)}</div><div className="mt-6 font-mono text-xs tracking-[.18em] text-jelly">{String(phase+1).padStart(2,"0")} / 05 · {phases[phase]}</div></div><div className="p-10"><div className="label-eyebrow mb-5">LIVE BUILD QUEUE</div><div className="space-y-3">{jobs.map((j,i)=><div key={j.id} className={`rounded-[1.5rem] border p-4 ${j.status==="building"?"border-jelly/30 bg-sinbad/20":j.status==="failed"?"border-milan/25 bg-milan/5":"border-rule bg-white"}`}><div className="flex gap-3"><span className="font-mono text-xs text-jelly">0{i+1}</span><div><b className="text-sm text-ink">{j.headline}</b><div className="text-xs text-dim mt-1">{j.status==="building"?phases[phase]:j.message??"Waiting in queue…"}</div></div></div></div>)}</div><div className="mt-7 text-[10px] font-mono tracking-[.14em] text-dim leading-5">THE ENGINE IS FINDING SOURCES, RANKING MOMENTS AND ASSEMBLING AN EDITOR-READY RECIPE.</div></div></div></div><style jsx global>{`@keyframes float{0%,100%{transform:translate3d(0,0,15px) rotate(-2deg)}50%{transform:translate3d(0,-12px,45px) rotate(2deg)}}`}</style></div>,document.body):null;
 return <><div className="space-y-7"><div className="soft-card p-6 flex items-end justify-between gap-5"><div><div className="label-eyebrow mb-1">FILM ROOM / EDITORIAL DESK</div><h2 className="font-display text-3xl tracking-wide text-ink">TODAY'S RECOMMENDED TWO</h2><p className="text-dim text-sm mt-1 max-w-2xl">The Brain picks two for follower growth, entertainment and Film Room identity. Fire ranks viral potential; the category badge tells you the editorial lane.</p></div><div className="text-right shrink-0"><div className="font-mono text-xs tracking-[.16em] text-dim mb-2">{selected.length} SELECTED · 2/DAY TARGET</div><button onClick={build} disabled={!selected.length||loading} className="btn-primary disabled:opacity-40">Build {selected.length} Selected Reel{selected.length===1?"":"s"}</button></div></div>{pairing&&<div className="pairing-note"><span>PAIRING LOGIC</span>{pairing}</div>}{error&&<div className="rounded-3xl border border-milan/20 bg-milan/5 px-5 py-4 text-signal text-sm">{error}</div>}<div className="grid md:grid-cols-2 gap-5">{picks.map((p,i)=>card(p,i))}</div><div><div className="flex items-end justify-between mb-3"><div><div className="label-eyebrow">OTHER LANES</div><h3 className="font-display text-2xl tracking-wide text-ink">THREE STRONG ALTERNATES</h3></div><div className="text-xs text-dim">Swap one in · or build a third</div></div><div className="grid lg:grid-cols-3 gap-4">{alts.map((p,i)=>card(p,i+2))}</div></div><button onClick={generateMore} disabled={moreLoading||loading} className="w-full min-h-[140px] rounded-[2rem] border border-dashed border-jelly/30 bg-sinbad/8 hover:bg-sinbad/14 flex items-center justify-center gap-5 p-7"><span className="orb-button">+</span><div className="text-left"><div className="font-display text-xl tracking-wide text-ink">{moreLoading?"THINKING…":"GENERATE ANOTHER ANGLE"}</div><div className="text-xs text-dim mt-1">One more fresh option without replacing the board.</div></div></button></div>{overlay}</>;
}
