"use client";
import { useMemo,useState } from "react";import { useRouter } from "next/navigation";
type Pitch={id:string;headline:string;sport:string;summary:string|null;score:number|null;score_breakdown:any;selected:boolean};type JobState={id:string;headline:string;status:"queued"|"building"|"ready"|"failed";message?:string};
const formatNames:any={INTERVIEW_STORY:"INTERVIEW → STORY",PLAYER_HIGHLIGHT:"PLAYER SPOTLIGHT",TEAM_HIGHLIGHT:"SCHOOL FEATURE",RIVALRY:"RIVALRY",MOMENT:"ICONIC MOMENT",STORY:"STORY"};
export default function PitchBoard({pitches}:{pitches:Pitch[]}){const router=useRouter();const[selected,setSelected]=useState<string[]>([]);const[loading,setLoading]=useState(false);const[moreLoading,setMoreLoading]=useState(false);const[error,setError]=useState<string|null>(null);const[jobs,setJobs]=useState<JobState[]>([]);const selectedSet=useMemo(()=>new Set(selected),[selected]);
function toggle(id:string){setSelected(c=>c.includes(id)?c.filter(x=>x!==id):c.length>=3?c:[...c,id]);}
async function generateOneMore(){setMoreLoading(true);setError(null);try{const res=await fetch("/api/generate-more-pitch",{method:"POST"});const raw=await res.text();let data:any={};try{data=raw?JSON.parse(raw):{}}catch{}if(!res.ok||data?.error)throw new Error(data?.error??`Could not generate another pitch (${res.status})`);router.refresh();}catch(e:any){setError(e?.message??"Could not generate another pitch.");}finally{setMoreLoading(false)}}
async function callBuild(id:string,slot:number){const res=await fetch("/api/build-one",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,slot})});const raw=await res.text();let data:any={};try{data=raw?JSON.parse(raw):{}}catch{throw new Error(`Server returned an unreadable response (${res.status}).`)}if(!res.ok||data?.error)throw new Error(data?.error??`Build failed (${res.status})`);return data;}
async function buildSelected(){if(selected.length!==3)return;setLoading(true);setError(null);const chosen=selected.map(id=>pitches.find(p=>p.id===id)!).filter(Boolean);setJobs(chosen.map(p=>({id:p.id,headline:p.headline,status:"queued"})));let ready=0;for(let i=0;i<chosen.length;i++){const pitch=chosen[i];setJobs(c=>c.map(j=>j.id===pitch.id?{...j,status:"building",message:"Searching interviews, broadcasts and highlight sources…"}:j));try{await callBuild(pitch.id,i+1);ready++;setJobs(c=>c.map(j=>j.id===pitch.id?{...j,status:"ready",message:"Editor-ready recipe built."}:j))}catch(e:any){setJobs(c=>c.map(j=>j.id===pitch.id?{...j,status:"failed",message:e?.message??"Build failed"}:j))}}setLoading(false);if(ready>0)router.refresh();if(ready<3)setError(`${ready}/3 reels built successfully. Failed pitches can be replaced without losing successful ones.`)}
return <><div className="space-y-5"><div className="soft-card p-6 flex items-end justify-between gap-5"><div><div className="label-eyebrow mb-1">FILM ROOM INTELLIGENCE / TODAY</div><h2 className="font-display text-3xl tracking-wide text-ink">CHOOSE THE THREE TO BUILD</h2><p className="text-dim text-sm mt-1">Five different editorial angles — interviews, players, schools, rivalries and stories — ranked for your channel.</p></div><div className="text-right shrink-0"><div className="font-mono text-xs tracking-[.16em] text-dim mb-2">{selected.length}/3 LOCKED</div><button onClick={buildSelected} disabled={selected.length!==3||loading} className="btn-primary disabled:opacity-40">Build 3 Selected Reels</button></div></div>{error&&<div className="rounded-xl border border-milan/20 bg-milan/5 px-4 py-3 text-signal text-sm">{error}</div>}
<div className="grid md:grid-cols-2 gap-4">{pitches.map((pitch,index)=>{const active=selectedSet.has(pitch.id),meta=pitch.score_breakdown??{},teams=Array.isArray(meta.teams)?meta.teams:meta.story?.teams??[],players=Array.isArray(meta.players)?meta.players:meta.story?.players??[],year=meta.year??meta.story?.year??"—",len=meta.anticipated_length??meta.story?.anticipatedLength??"20–30 sec",template=meta.template??meta.story?.template??"STORY",opening=meta.opening_concept??meta.story?.openingConcept,clipPlan=meta.clip_plan??meta.story?.clipPlan;return <button key={pitch.id} onClick={()=>toggle(pitch.id)} disabled={loading} style={{animationDelay:`${index*70}ms`}} className={`text-left panel pitch-card p-6 ${active?"ring-2 ring-jelly/35 bg-sidecar/70 -translate-y-1":"hover:bg-white"}`}><div className="flex items-center justify-between gap-4 mb-4"><div className="flex items-center gap-2 flex-wrap"><span className="font-mono text-[10px] tracking-[.18em] text-dim">OPTION {String(index+1).padStart(2,"0")}</span><span className="format-chip">{formatNames[template]??template}</span><span className="rounded-full bg-sidecar px-2 py-1 font-mono text-[9px] tracking-[.14em] text-ink/70">{String(pitch.sport).toUpperCase()}</span></div><span className={`h-6 w-6 grid place-items-center rounded-full border text-xs transition-all ${active?"border-jelly bg-jelly text-white scale-110":"border-rule bg-white text-transparent"}`}>✓</span></div><h3 className="font-display text-2xl tracking-wide text-ink mb-2">{pitch.headline}</h3><p className="text-sm text-dim leading-6 mb-4">{pitch.summary}</p>
<div className="grid grid-cols-2 gap-3 mb-4 text-xs"><div className="data-cell"><div className="data-label">TEAMS / SCHOOL</div><div className="text-ink font-medium">{teams.length?teams.join(" vs. "):"TBD"}</div></div><div className="data-cell warm"><div className="data-label">ERA</div><div className="text-ink font-medium">{year}</div></div><div className="data-cell col-span-2"><div className="data-label">PEOPLE TO KNOW</div><div className="text-ink/80">{players.length?players.join(" · "):"No specific player required"}</div></div></div>
{opening&&<div className="intel-strip"><span>OPEN</span><p>{opening}</p></div>}{clipPlan&&<div className="intel-strip"><span>EDIT</span><p>{clipPlan}</p></div>}
<div className="border-t border-rule pt-4 mt-4 space-y-3"><div className="text-xs leading-5"><span className="text-dim">WHY IT WORKS — </span><span className="text-ink/80">{meta.why_today??"Strong Film Room idea."}</span></div><div className="flex items-center justify-between text-xs font-mono tracking-wider text-dim"><span className="text-jelly">EST. {len}</span><span>FIT {Number(pitch.score??0).toFixed(1)}</span></div></div></button>})}
<button onClick={generateOneMore} disabled={moreLoading||loading} className="min-h-[280px] rounded-2xl border border-dashed border-jelly/30 bg-sinbad/8 hover:bg-sinbad/14 hover:border-jelly/50 transition-all duration-300 group flex flex-col items-center justify-center text-center p-8"><span className="orb-button mb-4">+</span><span className="font-display text-xl tracking-wide text-ink">{moreLoading?"THINKING…":"GENERATE ANOTHER ANGLE"}</span><span className="text-xs text-dim mt-2 max-w-[240px]">Adds one new editorial direction without replacing this board.</span></button></div></div>
{loading&&<div className="fixed inset-0 z-50 intelligence-overlay flex items-center justify-center p-6"><div className="w-full max-w-2xl intelligence-console"><div className="scanline"/><div className="border-b border-rule px-7 py-5 flex items-center justify-between"><div><div className="label-eyebrow mb-1">FILM ROOM / ACTIVE BUILD</div><div className="font-display text-2xl tracking-wide text-ink">ASSEMBLING YOUR EDIT RECIPES</div></div><div className="radar-orb"/></div><div className="px-7 py-6 space-y-3">{jobs.map((job,i)=><div key={job.id} className="job-row"><div><div className="data-label">REEL {String(i+1).padStart(2,"0")}</div><div className="font-display text-lg tracking-wide text-ink mt-1">{job.headline}</div>{job.message&&<div className="text-xs text-dim mt-2">{job.message}</div>}</div><div className={`font-mono text-xs tracking-wider ${job.status==="ready"?"text-go":job.status==="failed"?"text-signal":job.status==="building"?"text-jelly":"text-dim"}`}>{job.status==="ready"?"✓ READY":job.status==="failed"?"× FAILED":job.status==="building"?"● ANALYZING":"○ QUEUED"}</div></div>)}</div><div className="border-t border-rule px-7 py-4 font-mono text-[10px] tracking-[.16em] text-dim">SOURCE SEARCH · INTERVIEW CHECK · CLIP STRUCTURE · EDITORIAL FIT</div></div></div>}</>}
