import { NextResponse } from "next/server";
import { getBrandBrain } from "@/lib/getBrandBrain";
import { supabaseAdmin } from "@/lib/supabaseServer";
import { requireOwner } from "@/lib/requireOwner";

export const maxDuration = 60;
const ANTHROPIC_API_URL = "https://api.anthropic.com/v1/messages";
const PITCH_MODEL = process.env.ANTHROPIC_PITCH_MODEL ?? "claude-haiku-4-5";

type PitchStory = {headline:string;sport:"football"|"basketball";summary:string;whyToday:string;viewerFeeling:string;searchQueries:string[];popularityEvidence:string[];trendSources:{label:string;url:string}[];template:"INTERVIEW_STORY"|"PLAYER_HIGHLIGHT"|"TEAM_HIGHLIGHT"|"RIVALRY"|"MOMENT"|"STORY";fanAllegianceLogic:string;teams:string[];year:string;players:string[];anticipatedLength:string;openingConcept:string;clipPlan:string;recommendation:"PRIMARY"|"SECONDARY"|"ALTERNATE";recommendationReason:string;growthScore:number;entertainmentScore:number;brandScore:number;timelinessScore:number;editabilityScore:number;overallScore:number;pairingLogic:string;};

const baseFallback:any[]=[
 {headline:"Johnny Manziel made Alabama look mortal",sport:"football",summary:"Open with a short Johnny Manziel interview beat, then cut hard into the 2012 Alabama upset, escapes, deep balls and Mike Evans connections.",whyToday:"A recognizable personality plus elite highlights gives the reel a story and immediate stop-scroll value.",viewerFeeling:"swagger and nostalgia",searchQueries:["Johnny Manziel interview Texas A&M 2012 Alabama","Johnny Manziel Alabama 2012 highlights"],template:"INTERVIEW_STORY",teams:["Texas A&M","Alabama"],year:"2012",players:["Johnny Manziel","Mike Evans","AJ McCarron"],anticipatedLength:"22–30 sec",openingConcept:"3–6 second verified Manziel soundbite, then immediate beat drop.",clipPlan:"Interview hook → Alabama highlights from 2+ sources → final reaction."},
 {headline:"Reggie Bush looked like a video game at USC",sport:"football",summary:"A pure player spotlight using the most impossible cuts, returns and open-field moments from Bush's USC run.",whyToday:"Instantly understandable greatness, huge name recognition and endlessly rewatchable highlights.",viewerFeeling:"disbelief",searchQueries:["Reggie Bush USC best highlights 2005","Reggie Bush USC punt return highlights"],template:"PLAYER_HIGHLIGHT",teams:["USC"],year:"2004–05",players:["Reggie Bush","Matt Leinart"],anticipatedLength:"17–23 sec",openingConcept:"Start on one absurd change-of-direction clip before revealing the title.",clipPlan:"Cold-open highlight → 5–7 escalating plays from multiple games → celebration."},
 {headline:"Cam Newton's Auburn season still doesn't make sense",sport:"football",summary:"Center the 2010 run on power, escapes, touchdown celebrations and the championship finish.",whyToday:"One-player dominance reels are easy to understand and highly shareable.",viewerFeeling:"awe",searchQueries:["Cam Newton Auburn 2010 best highlights","Cam Newton LSU run 2010 Auburn"],template:"PLAYER_HIGHLIGHT",teams:["Auburn"],year:"2010",players:["Cam Newton"],anticipatedLength:"18–25 sec",openingConcept:"Open with the LSU run or another physically absurd play.",clipPlan:"Signature play → escalating run/pass highlights → championship payoff."},
 {headline:"Joe Burrow's 2019 LSU offense was unfair",sport:"football",summary:"A school-and-star highlight reel built around Burrow, Jefferson and Chase shredding elite opponents on the title run.",whyToday:"Modern stars, championship stakes and NFL-recognizable names give it broad appeal.",viewerFeeling:"dominance",searchQueries:["Joe Burrow LSU 2019 best highlights","LSU 2019 offense Jefferson Chase highlights"],template:"TEAM_HIGHLIGHT",teams:["LSU"],year:"2019",players:["Joe Burrow","Justin Jefferson","Ja'Marr Chase"],anticipatedLength:"20–27 sec",openingConcept:"Open on a Burrow touchdown against a ranked opponent.",clipPlan:"Burrow hook → Jefferson/Chase explosives → title-game payoff."},
 {headline:"Kick Six — the ending that broke the Iron Bowl",sport:"football",summary:"Build just enough rivalry stakes, then let the missed field goal, Chris Davis return and broadcast chaos carry the reel.",whyToday:"A legendary play with built-in context, recognition and emotional payoff.",viewerFeeling:"shock and chaos",searchQueries:["Auburn Alabama Kick Six 2013 broadcast","Kick Six alternate angles crowd"],template:"MOMENT",teams:["Auburn","Alabama"],year:"2013",players:["Chris Davis","Nick Marshall","AJ McCarron"],anticipatedLength:"18–25 sec",openingConcept:"One quick setup line, then the kick immediately.",clipPlan:"Setup → broadcast return → alternate angle → celebration payoff."}
];
function num(v:any,d=8){const n=Number(v);return Number.isFinite(n)?Math.max(0,Math.min(10,n)):d;}
function normalizeStory(s:any):PitchStory{return {headline:String(s.headline),sport:s.sport==="basketball"?"basketball":"football",summary:String(s.summary??""),whyToday:String(s.whyToday??"Strong Film Room idea."),viewerFeeling:String(s.viewerFeeling??"awe"),searchQueries:Array.isArray(s.searchQueries)&&s.searchQueries.length?s.searchQueries.slice(0,4).map(String):[String(s.headline)],popularityEvidence:Array.isArray(s.popularityEvidence)?s.popularityEvidence.map(String):[],trendSources:[],template:["INTERVIEW_STORY","PLAYER_HIGHLIGHT","TEAM_HIGHLIGHT","RIVALRY","MOMENT","STORY"].includes(s.template)?s.template:"PLAYER_HIGHLIGHT",fanAllegianceLogic:String(s.fanAllegianceLogic??"Keep one emotional point of view."),teams:Array.isArray(s.teams)?s.teams.slice(0,4).map(String):[],year:String(s.year??"—"),players:Array.isArray(s.players)?s.players.slice(0,6).map(String):[],anticipatedLength:String(s.anticipatedLength??"20–30 sec"),openingConcept:String(s.openingConcept??"Open on the strongest visual."),clipPlan:String(s.clipPlan??"Hook → escalating highlights → payoff."),recommendation:["PRIMARY","SECONDARY","ALTERNATE"].includes(s.recommendation)?s.recommendation:"ALTERNATE",recommendationReason:String(s.recommendationReason??"Strong Film Room option."),growthScore:num(s.growthScore),entertainmentScore:num(s.entertainmentScore),brandScore:num(s.brandScore),timelinessScore:num(s.timelinessScore),editabilityScore:num(s.editabilityScore),overallScore:num(s.overallScore),pairingLogic:String(s.pairingLogic??"")};}
function fallbackPitches():PitchStory[]{return baseFallback.map((s:any,i:number)=>normalizeStory({...s,recommendation:i===0?"PRIMARY":i===1?"SECONDARY":"ALTERNATE",recommendationReason:i===0?"Best blend of recognizable star, story hook and elite highlight payoff.":i===1?"Pure viral highlight energy that complements the story-led primary.":"Strong alternate lane.",growthScore:[9.6,9.4,9.0,9.1,9.2][i],entertainmentScore:[9.5,9.7,9.2,9.2,9.6][i],brandScore:[9.7,9.4,9.2,9.3,9.4][i],timelinessScore:[8.2,8.0,7.8,8.1,7.7][i],editabilityScore:[9.3,9.7,9.5,9.5,9.6][i],overallScore:[9.4,9.4,9.0,9.1,9.3][i],pairingLogic:i<2?"One story-led star reel plus one pure highlight reel gives today's feed range without sacrificing energy.":"Alternate editorial lane."}));}
function extractJson(text:string){const cleaned=text.trim().replace(/^```json\s*/i,"").replace(/^```\s*/i,"").replace(/```$/i,"").trim();try{return JSON.parse(cleaned);}catch{const start=cleaned.indexOf("{");const end=cleaned.lastIndexOf("}");if(start>=0&&end>start)return JSON.parse(cleaned.slice(start,end+1));throw new Error("Unreadable pitch response");}}

async function generatePitchIdeas(dateIso:string,brain:any,rejectionMemory:string):Promise<PitchStory[]>{
 const apiKey=process.env.ANTHROPIC_API_KEY;if(!apiKey)return fallbackPitches();
 const prompt=`You are the editorial director and growth strategist for Film Room, a cinematic MEN'S college sports short-form brand. Today is ${dateIso}. Brand thesis: make today's college sports feel historic and historic college sports feel alive again. Voice: ${(brain?.voice?.principles??[]).join(" ")}.

CRITICAL CONTENT RULES:
- MEN'S COLLEGE SPORTS ONLY. Never pitch women's sports or women's players.
- It is football season, so today's board should normally be 4-5 COLLEGE FOOTBALL ideas. At most one men's college basketball pitch, and only if it is exceptional or timely.
- HIGHLIGHTS ARE THE CORE PRODUCT. Favor explosive plays, superstar players, iconic teams, rivalries and unforgettable moments. Do not pitch marching bands, generic crowd noise, entrances, stadium atmosphere or traditions as the main subject.
- The four editorial lanes are: PLAYER_HIGHLIGHT = spotlight player; TEAM_HIGHLIGHT = spotlight school/team through on-field highlights; MOMENT or RIVALRY = highlight-driven iconic game/play; INTERVIEW_STORY or STORY = story/testimony where a verified interview/documentary soundbite creates a short hook and HIGHLIGHTS carry the majority of the reel.
- Every idea must have enough searchable footage to pull from AT LEAST TWO source videos.
- Use real teams, years and recognizable male players. Usually 15-35 seconds.
- Never repeat an idea the owner has rejected. Learn from rejection patterns, not just exact headlines.

REJECTION MEMORY FROM PREVIOUS FILM ROOM DECISIONS:
${rejectionMemory || "No rejection feedback recorded yet."}

Generate exactly FIVE fresh pitches. Label exactly ONE PRIMARY, exactly ONE SECONDARY, and THREE ALTERNATE. PRIMARY and SECONDARY are the two Film Room should post: optimize for follower growth + entertainment + long-term brand identity. Do not merely choose two similar high scores.
Score each 0-10: Growth Potential 30%; Entertainment/Emotional Pull 25%; Film Room Brand Fit 25%; Timeliness 10%; Source/Edit Potential 10%. A 9.3+ overall should be genuinely FIRE: unusually strong viral/rewatch/share potential, not handed out casually.
For PRIMARY and SECONDARY explain why the Brain picked it and why the pair belongs together.
Return ONLY valid JSON: {"stories":[{"headline":"...","sport":"football|basketball","summary":"...","whyToday":"...","viewerFeeling":"...","searchQueries":["..."],"popularityEvidence":["..."],"trendSources":[],"template":"INTERVIEW_STORY|PLAYER_HIGHLIGHT|TEAM_HIGHLIGHT|RIVALRY|MOMENT|STORY","fanAllegianceLogic":"...","teams":["..."],"year":"...","players":["..."],"anticipatedLength":"...","openingConcept":"...","clipPlan":"...","recommendation":"PRIMARY|SECONDARY|ALTERNATE","recommendationReason":"...","growthScore":9.2,"entertainmentScore":9.0,"brandScore":9.5,"timelinessScore":8.0,"editabilityScore":9.1,"overallScore":9.1,"pairingLogic":"..."}]}`;
 const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),14000);
 try{const response=await fetch(ANTHROPIC_API_URL,{method:"POST",headers:{"content-type":"application/json","x-api-key":apiKey,"anthropic-version":"2023-06-01"},body:JSON.stringify({model:PITCH_MODEL,max_tokens:3000,temperature:.72,messages:[{role:"user",content:prompt}]}),signal:controller.signal});const payload=await response.json();if(!response.ok)throw new Error(payload?.error?.message??`Anthropic request failed (${response.status})`);const text=(payload?.content??[]).filter((b:any)=>b?.type==="text").map((b:any)=>b.text).join("\n");const parsed=extractJson(text);const normalized:PitchStory[]=(Array.isArray(parsed?.stories)?parsed.stories:[]).filter((s:any)=>s?.headline&&(s.sport==="football"||s.sport==="basketball")).slice(0,5).map(normalizeStory);if(normalized.length!==5)return fallbackPitches();const primary=normalized.filter((s:PitchStory)=>s.recommendation==="PRIMARY");const secondary=normalized.filter((s:PitchStory)=>s.recommendation==="SECONDARY");if(primary.length!==1||secondary.length!==1){const sorted=[...normalized].sort((a,b)=>b.overallScore-a.overallScore);sorted.forEach((s,i)=>s.recommendation=i===0?"PRIMARY":i===1?"SECONDARY":"ALTERNATE");return sorted;}return [...primary,...secondary,...normalized.filter(s=>s.recommendation==="ALTERNATE").sort((a,b)=>b.overallScore-a.overallScore)];}catch(error){console.warn("Pitch AI unavailable; using fallback.",error);return fallbackPitches();}finally{clearTimeout(timer);}
}

export async function POST(){try{await requireOwner();const brain=await getBrandBrain();const db=supabaseAdmin();const today=new Date().toISOString().slice(0,10);const {data:rejected}=await db.from("reels").select("headline,review_note,recipe,status").eq("status","rejected").order("updated_at",{ascending:false}).limit(30);const rejectionMemory=(rejected??[]).map((r:any)=>`- ${r.headline}${r.review_note?` — reason: ${r.review_note}`:""}${r.recipe?.template?` — style: ${r.recipe.template}`:""}`).join("\n");const stories=await generatePitchIdeas(today,brain,rejectionMemory);const pitchRows=stories.map((story:PitchStory)=>({slate_date:today,candidate_kind:"pitch",headline:story.headline,sport:story.sport,summary:story.summary,source_urls:[],score:story.overallScore,score_breakdown:{story,kind:"pitch",why_today:story.whyToday,viewer_feeling:story.viewerFeeling,template:story.template,fan_allegiance_logic:story.fanAllegianceLogic,teams:story.teams,year:story.year,players:story.players,anticipated_length:story.anticipatedLength,opening_concept:story.openingConcept,clip_plan:story.clipPlan,recommendation:story.recommendation,recommendation_reason:story.recommendationReason,pairing_logic:story.pairingLogic,growth_score:story.growthScore,entertainment_score:story.entertainmentScore,brand_score:story.brandScore,timeliness_score:story.timelinessScore,editability_score:story.editabilityScore},selected:false,rejection_reason:null}));const{error:deleteError}=await db.from("candidates").delete().eq("slate_date",today).eq("candidate_kind","pitch");if(deleteError)throw deleteError;const{data,error}=await db.from("candidates").insert(pitchRows).select();if(error)throw error;return NextResponse.json({pitches:data??[],count:data?.length??0});}catch(err:any){console.error("Pitch generation failed:",err);const status=err?.message==="UNAUTHORIZED"?401:err?.message==="FORBIDDEN"?403:500;return NextResponse.json({error:status===401?"Please sign in again.":status===403?"Owner access required.":err?.message??"Pitch generation failed"},{status});}}
