import { NextResponse } from "next/server";
import { getBrandBrain } from "@/lib/getBrandBrain";
import { supabaseAdmin } from "@/lib/supabaseServer";
import { requireOwner } from "@/lib/requireOwner";

export const maxDuration = 60;
const ANTHROPIC_API_URL = "https://api.anthropic.com/v1/messages";
const PITCH_MODEL = process.env.ANTHROPIC_PITCH_MODEL ?? "claude-haiku-4-5";

type PitchStory = {headline:string;sport:"football"|"basketball";summary:string;whyToday:string;viewerFeeling:string;searchQueries:string[];popularityEvidence:string[];trendSources:{label:string;url:string}[];template:"INTERVIEW_STORY"|"PLAYER_HIGHLIGHT"|"TEAM_HIGHLIGHT"|"RIVALRY"|"MOMENT"|"STORY";fanAllegianceLogic:string;teams:string[];year:string;players:string[];anticipatedLength:string;openingConcept:string;clipPlan:string;recommendation:"PRIMARY"|"SECONDARY"|"ALTERNATE";recommendationReason:string;growthScore:number;entertainmentScore:number;brandScore:number;timelinessScore:number;editabilityScore:number;overallScore:number;pairingLogic:string;};
const baseFallback:any[]=[
 {headline:"Johnny Manziel explains the chaos — then show it",sport:"football",summary:"Open on a strong Johnny Manziel interview or documentary soundbite about his college mindset, then smash into the Alabama upset, escapes and Mike Evans connections.",whyToday:"A personality-led opening makes familiar highlights feel like a story instead of another montage.",viewerFeeling:"swagger and nostalgia",searchQueries:["Johnny Manziel interview Texas A&M documentary college football","Johnny Manziel Alabama 2012 highlights"],template:"INTERVIEW_STORY",teams:["Texas A&M","Alabama"],year:"2012",players:["Johnny Manziel","Mike Evans","AJ McCarron"],anticipatedLength:"24–32 sec",openingConcept:"4–7 sec interview quote about pressure, confidence or the Alabama game.",clipPlan:"Interview cold open → beat/drop → 3–5 Manziel highlights → crowd/final reaction."},
 {headline:"Caitlin Clark from logo range",sport:"basketball",summary:"A clean player reel built around Clark's deepest threes, swagger and Iowa crowd reactions.",whyToday:"Basketball keeps the feed varied and the skill is instantly legible.",viewerFeeling:"disbelief and admiration",searchQueries:["Caitlin Clark Iowa logo threes highlights"],template:"PLAYER_HIGHLIGHT",teams:["Iowa"],year:"2023–24",players:["Caitlin Clark"],anticipatedLength:"16–22 sec",openingConcept:"Open on a stare-down or commentator setup about her range.",clipPlan:"Setup → progressively deeper threes → celebration/crowd payoff."},
 {headline:"Cam Newton was inevitable at Auburn",sport:"football",summary:"Center Cam Newton's 2010 season: power runs, impossible escapes, celebrations and championship imagery.",whyToday:"One-player identity reels are highly rewatchable.",viewerFeeling:"awe",searchQueries:["Cam Newton Auburn 2010 highlights"],template:"PLAYER_HIGHLIGHT",teams:["Auburn"],year:"2010",players:["Cam Newton"],anticipatedLength:"18–24 sec",openingConcept:"Close-up, tunnel shot or one-line quote before the music hits.",clipPlan:"Identity shot → 5–7 escalating highlights → championship payoff."},
 {headline:"Death Valley at night feels like another sport",sport:"football",summary:"Make LSU itself the subject: entrance, band, crowd, stadium lights and explosive home highlights.",whyToday:"School culture broadens the account beyond individual stars.",viewerFeeling:"belonging and atmosphere",searchQueries:["LSU Death Valley night game cinematic"],template:"TEAM_HIGHLIGHT",teams:["LSU"],year:"Multiple seasons",players:["Joe Burrow","Jayden Daniels"],anticipatedLength:"20–27 sec",openingConcept:"Quiet stadium/tunnel audio before the crowd erupts.",clipPlan:"Atmosphere → entrance → star highlights → crowd finish."},
 {headline:"Kick Six — rivalry hatred in one play",sport:"football",summary:"Build the Iron Bowl stakes quickly, then let the missed field goal, Chris Davis return and Jordan-Hare eruption carry the edit.",whyToday:"Rivalry stories have built-in context and emotion.",viewerFeeling:"shock and chaos",searchQueries:["Auburn Alabama Kick Six 2013 broadcast"],template:"RIVALRY",teams:["Auburn","Alabama"],year:"2013",players:["Chris Davis","Nick Marshall","AJ McCarron"],anticipatedLength:"20–26 sec",openingConcept:"One sentence of rivalry context before the kick.",clipPlan:"Rivalry setup → kick → full return → crowd/broadcast payoff."}
];
function fallbackPitches():PitchStory[]{return baseFallback.map((s,i)=>normalizeStory({...s,recommendation:i===0?"PRIMARY":i===1?"SECONDARY":"ALTERNATE",recommendationReason:i===0?"Best combination of recognizable personality, narrative hook, nostalgia and highlight payoff.":i===1?"Strong growth idea that complements the primary with a different sport and visual rhythm.":"Strong backup option if you want a different tone or a third post.",growthScore:[9.5,9.2,8.8,8.3,8.5][i],entertainmentScore:[9.4,9.2,9,8.6,9.2][i],brandScore:[9.7,9,9.1,9.3,9.1][i],timelinessScore:[7.8,8,7.5,7.7,7.5][i],editabilityScore:[9.2,9.5,9.4,9,9.5][i],overallScore:[9.3,9.1,8.7,8.5,8.6][i],pairingLogic:i<2?"The two recommendations intentionally differ in sport, tone and storytelling format so the feed feels curated rather than repetitive.":"Alternate editorial lane."}));}
function num(v:any,d=8){const n=Number(v);return Number.isFinite(n)?Math.max(0,Math.min(10,n)):d;}
function normalizeStory(s:any):PitchStory{return {headline:String(s.headline),sport:s.sport==="basketball"?"basketball":"football",summary:String(s.summary??""),whyToday:String(s.whyToday??"Seasonally relevant Film Room idea."),viewerFeeling:String(s.viewerFeeling??"nostalgia or excitement"),searchQueries:Array.isArray(s.searchQueries)&&s.searchQueries.length?s.searchQueries.slice(0,4).map(String):[String(s.headline)],popularityEvidence:Array.isArray(s.popularityEvidence)?s.popularityEvidence.map(String):[],trendSources:[],template:["INTERVIEW_STORY","PLAYER_HIGHLIGHT","TEAM_HIGHLIGHT","RIVALRY","MOMENT","STORY"].includes(s.template)?s.template:"STORY",fanAllegianceLogic:String(s.fanAllegianceLogic??"Keep one emotional point of view."),teams:Array.isArray(s.teams)?s.teams.slice(0,4).map(String):[],year:String(s.year??"—"),players:Array.isArray(s.players)?s.players.slice(0,6).map(String):[],anticipatedLength:String(s.anticipatedLength??"20–30 sec"),openingConcept:String(s.openingConcept??"Open with the strongest context before the highlights."),clipPlan:String(s.clipPlan??"Hook → escalating highlights → payoff."),recommendation:["PRIMARY","SECONDARY","ALTERNATE"].includes(s.recommendation)?s.recommendation:"ALTERNATE",recommendationReason:String(s.recommendationReason??"Strong Film Room option."),growthScore:num(s.growthScore),entertainmentScore:num(s.entertainmentScore),brandScore:num(s.brandScore),timelinessScore:num(s.timelinessScore),editabilityScore:num(s.editabilityScore),overallScore:num(s.overallScore),pairingLogic:String(s.pairingLogic??"")};}
function extractJson(text:string){const cleaned=text.trim().replace(/^```json\s*/i,"").replace(/^```\s*/i,"").replace(/```$/i,"").trim();try{return JSON.parse(cleaned);}catch{const start=cleaned.indexOf("{");const end=cleaned.lastIndexOf("}");if(start>=0&&end>start)return JSON.parse(cleaned.slice(start,end+1));throw new Error("Unreadable pitch response");}}
async function generatePitchIdeas(dateIso:string,brain:any):Promise<PitchStory[]>{const apiKey=process.env.ANTHROPIC_API_KEY;if(!apiKey)return fallbackPitches();const prompt=`You are the editorial director and growth strategist for Film Room, a cinematic college football + basketball short-form brand. Today is ${dateIso}. Brand thesis: make today's college sports feel historic and historic college sports feel alive again. Voice: ${(brain?.voice?.principles??[]).join(" ")}.
The account normally POSTS TWICE PER DAY and wants to stay about TWO DAYS AHEAD, but live games/breaking moments can override evergreen plans. Generate exactly FIVE specific pitches, then make an editorial decision: label exactly ONE PRIMARY, exactly ONE SECONDARY, and THREE ALTERNATE.
PRIMARY = the post you believe has the highest chance to attract followers while strengthening Film Room. SECONDARY = the best companion post for the same day; do NOT merely choose the #2 individual score. It should complement the primary in sport, era, emotional tone, school/player, or format so the feed feels intentional. ALTERNATES = genuinely strong backups or a third-post option.
Score each pitch 0-10 using this editorial model: Growth Potential 30% (stop-scroll, shares, follows, broad recognition); Entertainment/Emotional Pull 25% (awe, chills, humor, disbelief, rivalry, nostalgia, swagger); Film Room Brand Fit 25% (cinematic, story-first, feels distinctive rather than generic highlights); Timeliness 10%; Source/Edit Potential 10%. Return each component plus overallScore. Protect long-term brand strength over cheap trend chasing.
Formats: INTERVIEW_STORY (verified/searchable interview or documentary soundbite as 3–8 sec cold open then highlights; NEVER invent quotes/interviews), PLAYER_HIGHLIGHT, TEAM_HIGHLIGHT, RIVALRY, MOMENT, STORY. Use real teams, years and recognizable players. Quiet news days are fine: evergreen history, school culture, interviews and legendary players are valuable. Favor searchable footage. Usually 15–35 sec.
For the PRIMARY and SECONDARY, recommendationReason must clearly explain WHY THE BRAIN PICKED IT. pairingLogic must explain why those two belong together as today's pair. Avoid recommending two nearly identical subjects.
Return ONLY valid JSON: {"stories":[{"headline":"...","sport":"football|basketball","summary":"...","whyToday":"...","viewerFeeling":"...","searchQueries":["..."],"popularityEvidence":["..."],"trendSources":[],"template":"INTERVIEW_STORY|PLAYER_HIGHLIGHT|TEAM_HIGHLIGHT|RIVALRY|MOMENT|STORY","fanAllegianceLogic":"...","teams":["..."],"year":"...","players":["..."],"anticipatedLength":"...","openingConcept":"...","clipPlan":"...","recommendation":"PRIMARY|SECONDARY|ALTERNATE","recommendationReason":"...","growthScore":9.2,"entertainmentScore":9.0,"brandScore":9.5,"timelinessScore":8.0,"editabilityScore":9.1,"overallScore":9.1,"pairingLogic":"..."}]}`;const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),14000);try{const response=await fetch(ANTHROPIC_API_URL,{method:"POST",headers:{"content-type":"application/json","x-api-key":apiKey,"anthropic-version":"2023-06-01"},body:JSON.stringify({model:PITCH_MODEL,max_tokens:3000,temperature:.72,messages:[{role:"user",content:prompt}]}),signal:controller.signal});const payload=await response.json();if(!response.ok)throw new Error(payload?.error?.message??`Anthropic request failed (${response.status})`);const text=(payload?.content??[]).filter((b:any)=>b?.type==="text").map((b:any)=>b.text).join("\n");const parsed=extractJson(text);const normalized=(Array.isArray(parsed?.stories)?parsed.stories:[]).filter((s:any)=>s?.headline&&(s.sport==="football"||s.sport==="basketball")).slice(0,5).map(normalizeStory);if(normalized.length!==5)return fallbackPitches();const primary=normalized.filter(s=>s.recommendation==="PRIMARY"),secondary=normalized.filter(s=>s.recommendation==="SECONDARY");if(primary.length!==1||secondary.length!==1){const sorted=[...normalized].sort((a,b)=>b.overallScore-a.overallScore);sorted.forEach((s,i)=>s.recommendation=i===0?"PRIMARY":i===1?"SECONDARY":"ALTERNATE");return sorted;}return [...primary,...secondary,...normalized.filter(s=>s.recommendation==="ALTERNATE").sort((a,b)=>b.overallScore-a.overallScore)];}catch(error){console.warn("Pitch AI unavailable; using fallback.",error);return fallbackPitches();}finally{clearTimeout(timer);}}
export async function POST(){try{await requireOwner();const brain=await getBrandBrain();const db=supabaseAdmin();const today=new Date().toISOString().slice(0,10);const stories=await generatePitchIdeas(today,brain);const pitchRows=stories.map((story,index)=>({slate_date:today,candidate_kind:"pitch",headline:story.headline,sport:story.sport,summary:story.summary,source_urls:[],score:story.overallScore,score_breakdown:{story,kind:"pitch",why_today:story.whyToday,viewer_feeling:story.viewerFeeling,template:story.template,fan_allegiance_logic:story.fanAllegianceLogic,teams:story.teams,year:story.year,players:story.players,anticipated_length:story.anticipatedLength,opening_concept:story.openingConcept,clip_plan:story.clipPlan,recommendation:story.recommendation,recommendation_reason:story.recommendationReason,pairing_logic:story.pairingLogic,growth_score:story.growthScore,entertainment_score:story.entertainmentScore,brand_score:story.brandScore,timeliness_score:story.timelinessScore,editability_score:story.editabilityScore},selected:false,rejection_reason:null}));const{error:deleteError}=await db.from("candidates").delete().eq("slate_date",today).eq("candidate_kind","pitch");if(deleteError)throw deleteError;const{data,error}=await db.from("candidates").insert(pitchRows).select();if(error)throw error;return NextResponse.json({pitches:data??[],count:data?.length??0});}catch(err:any){console.error("Pitch generation failed:",err);const status=err?.message==="UNAUTHORIZED"?401:err?.message==="FORBIDDEN"?403:500;return NextResponse.json({error:status===401?"Please sign in again.":status===403?"Owner access required.":err?.message??"Pitch generation failed"},{status});}}
